seo:
  site_name: Karin Gütiger Awaken Soul
  title: ThetaHealing & Familienmediation Karin Gütiger Awaken Soul
  description:
  keywords:
  social_image: /uploads/pajuramacopyright-18.jpg
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/awakensoul.ch/
  facebook_url: https://www.facebook.com/profile.php?id=100086212285586
  telefon: +41786279656
  whatsapp_url: https://wa.me/41786279656
  email: info@karinguetiger.ch
design:
  dark-text_color: '#2e2e2e'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#CBAE6B'
  medium_color: '#E3BD63'
  light_color: '#F0E9D8'
  v-light_color: '#EFD69C'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
  accent_colors: '#ffffff'
